FROM kong:3.4

ENV KONG_PG_HOST="kong-database"
ENV KONG_PG_USER="kong"
ENV KONG_PG_PASSWORD="kong"
ENV KONG_PG_DATABASE="kong"

ENV KONG_LOG_LEVEL="error"

ENV KONG_ADMIN_LISTEN="0.0.0.0:8001, 0.0.0.0:8444 ssl" \
    KONG_ADMIN_GUI_API_URL="http://localhost:8001"

ENV KONG_ADMIN_GUI_LISTEN="0.0.0.0:8002, 0.0.0.0:8445 ssl" \
    KONG_ADMIN_GUI_PATH="/" \
    KONG_ADMIN_GUI_URL="http://0.0.0.0:8002"

ENV KONG_RBAC="on" \
    KONG_ENFORCE_RBAC="on" \
    KONG_ADMIN_GUI_AUTH="basic-auth"

EXPOSE 8000 8443 8001 8444 8002 8445

#RUN ["kong", "migrations", "bootstrap"]